server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

# URL MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diplomado?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDateTimeCode=false
    # Username and password
    username: root
    #spring.datasource.password = 5hmdzk4D!
    password: 1pt0t4l
    driverClassName: com.mysql.cj.jdbc.Driver


  # mostrar el SQl por consola
  jpa:
    show-sql: true

    # con update cada vez que se crea una entidad JPA crea una nueva tabla
    # si se modifica la entidad también se modifica su respectiva tabla
    hibernate:
      ddl-auto: update

    # permite a Hibernate generar SQL optimizado
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# values

jwt:
  secret: secret
  expiration: 36000

#spring.application.name = company-service

#eureka.client.serviceUrl.defaultZone = http://18.218.213.52:8761/:8761/eureka/,http://18.191.87.191:8762/
#spring.cloud.config.uri: http://eureka-peer1:8088

